services:
  postgres:
    image: postgres:13
    container_name: virality-postgres
    environment:
      POSTGRES_DB: virality_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGTZ: Asia/Kolkata
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: virality-redis
    ports:
      - "6379:6379"